# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown
kramdown:
  coderay_tab_width: 2
highlighter:         rouge #change highlighter at https://benhur07b.github.io/2017/03/25/add-syntax-highlighting-to-your-jekyll-site-with-rouge.html
# Setup
title:               Vinh Ng
tagline:             'blog'
description:         'A personal website of <a href="https://vinhintw.github.io/about" target="">Vinh Ng</a>, containing technical blog on technology.'
# url:
# baseurl:             'https://vinhintw.github.io'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
#gravatar_md5: 9e256a8aa4a000b36f6466983d423ba8480a71f807bf7aaa24f8947c6dc3a35e


# Build settings
theme: minima
plugins:
  - jekyll-paginate

author:
  name:              Vinh Ng
  facebook:          https://facebook.com/vinhintw.info
  email:             vinhintw2014@gmail.com
  github:            https://github.com/vinhintw

# Custom vars
version:             1.0.0